apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: serviceaccount-deploymemt
  name: serviceaccount-deploymemt
spec:
  replicas: 5
  selector:
    matchLabels:
      app: serviceaccount-deploymemt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: serviceaccount-deploymemt
    spec:
      serviceAccount: deployment
      containers:
      - command:
        - sleep
        - "3600"
        image: ubuntu
        name: ubuntu
        resources: {}
status: {}
