apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-03-14T07:46:16Z"
  labels:
    run: srviceaccount-pod
  name: serviceaccount-pod
  namespace: default
  resourceVersion: "246634"
  uid: 6bda17cf-5d57-4347-8dc8-db6c3fea37bd
spec:
  serviceAccount: deployment
  containers:
  - command:
    - sleep
    - "3600"
    image: ubuntu
    imagePullPolicy: Always
    name: ubuntu-container
    resources:
      requests:
        cpu: "1"
        memory: 1Gi
