apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-03-14T07:09:38Z"
  labels:
    run: resource-pod
  name: resource-pod
  namespace: default
  resourceVersion: "246162"
  uid: e6a11045-a671-44a6-a171-bac88ae24db0
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: ubuntu
    imagePullPolicy: Always
    name: ubuntu-container
    resources:
      requests:
        memory: "1Gi"
        cpu: 1  
