apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret3
  labels:
    name: mypod-secret3
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 8080

