apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret1
spec:
  containers:
  - name: mypod-secret1-container
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret1
