apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret2
spec:
  containers:
  - name: mypod-secret2-container
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret2
      items:
      - key: username
        path: my-group/my-username
