apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-03-14T06:29:05Z"
  labels:
    run: nginx-pod
  name: nginx-pod
  namespace: default
  resourceVersion: "243396"
  uid: f32059c3-ecf4-487c-8fc3-4359e748ac4d
spec:
  containers:
  - image: nginx
    name: nginx-pod
    envFrom:
    - secretRef:
        name: app-secret
